# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 714b5671c1b730a395e154358e314f24b7896dd5034114d1592e686bd3a1fff99ad5ce40a330759115ff48ea8dbbcc10d2b62cf6d622a5ffe02f7bddad0c4e8f

test:
  secret_key_base: 117839b71f8dc72965829bfcb3893260f65edc14160b8775b188938f44de7f34119933801fa205ff4cf81f82e6e29d3fb0e63dc43bc7875dda3f0920c4d97028

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
